// import Head from 'next/head'
// import Image from 'next/image'
import { useState } from 'react'
import { Button, Htag, P, Rating, Tag  } from '../components'
import { Layout, withLayout } from '../layout/Layout'

function Home(): JSX.Element {
  const [rating,setRating] = useState<number>(4)
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Htag tag="h1">Заголовок</Htag>
      <Button appearance="primary">Кнопка</Button>
      <Button appearance="ghost" arrow='right'>Кнопка</Button>
      <P size='l'>Большой</P>
      <P>Средний</P>
      <P size='s'>Маленький</P>

      <Tag size='s'>Ghost</Tag>
      <Tag size='m' color='red'>Red</Tag>
      <Tag size='m' color='green'>Green</Tag>
      <Rating isEditable rating={rating} setRating={setRating} />
    </>
  )
}

export default withLayout(Home)
